# Generated by Django 5.0 on 2023-12-11 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('rider_address', models.CharField(max_length=255)),
                ('rider_Phone_number', models.CharField(max_length=15)),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('series', models.CharField(max_length=255)),
                ('reserved_quantity', models.IntegerField()),
                ('amount_returned_by_customer', models.FloatField(max_length=255)),
                ('quantity_sold', models.CharField(max_length=255)),
                ('amount_charged', models.CharField(max_length=255)),
                ('gift_or_discount', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quantity_delivered', models.CharField(max_length=255)),
                ('amount_paid', models.CharField(max_length=255)),
                ('balance', models.FloatField(max_length=255)),
                ('discount', models.FloatField(max_length=255)),
                ('confirmed', models.BooleanField(default=False)),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rider.rider')),
            ],
        ),
    ]
