# Generated by Django 5.0 on 2023-12-16 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('series', models.CharField(max_length=255, null=True)),
                ('quantity_delivered', models.IntegerField(null=True)),
                ('amount_paid', models.FloatField(max_length=255, null=True)),
                ('balance', models.FloatField(max_length=255, null=True)),
                ('discount', models.FloatField(max_length=255, null=True)),
                ('confirmed', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
