# Generated by Django 5.0 on 2023-12-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('series', models.CharField(max_length=255)),
                ('quantity_delivered', models.CharField(max_length=255)),
                ('amount_paid', models.CharField(max_length=255)),
                ('balance', models.FloatField(max_length=255)),
                ('discount', models.FloatField(max_length=255)),
                ('confirmed', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending')], default='pending', max_length=20)),
            ],
        ),
    ]
