# Generated by Django 4.2.7 on 2023-12-08 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('reserved_quantity', models.IntegerField()),
                ('amount_returned_by_customer', models.FloatField(max_length=255)),
                ('quantity_sold', models.CharField(max_length=255)),
                ('amount_charged', models.CharField(max_length=255)),
                ('gift_or_discount', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('series', models.CharField(max_length=255)),
                ('quantity_delivered', models.CharField(max_length=255)),
                ('amount_paid', models.CharField(max_length=255)),
                ('balance', models.FloatField(max_length=255)),
                ('discount', models.FloatField(max_length=255)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
